name: Build and Deploy Code
on:
  push:
    branches:
      - "main"
jobs:
  job1:
    environment:
      name: testing
    # env for job1 ASD
    env:
      # DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
      # DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      # DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      # DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      # DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      # SECRET_KEY: ${{secrets.SECRET_KEY}}
      # ALGORITHM: ${{secrets.ALGORITHM}}
      # ACCESS_TOKEN_EXPIRE_MINUTES: 60
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: test.1234
      DATABASE_NAME: fastapi_test
      DATABASE_USERNAME: postgres
      SECRET_KEY: f03d476b8de3751b320b2cdd9ec6ce71d70cadebcde4fc73789e873829610d9f
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: test.1234
          POSTGRES_DB: fastapi_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: run pytest
        run: pytest -v -x -s  --disable-warnings
